# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 736f9a5c15a4dd08f742aae30b1848f117ea827b7a00325f474415536bb73fd51aaadf99dcdbd8730e4c97b3134421370da30d41d939b4717bcf1f5f1956e599

test:
  secret_key_base: cb3b67432e1c27a81ef42bc5ad91cf2cb7f0a1de7cabce2c3ca56f73eeb58009c1e49585029ed099678aaa4454f7a6a91b2219ea71428603d4ee55c93afa75c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
